# Site settings
course_name: PurS3cuRE Sessions
what: "Student driven weekly meetings where we will learn techniques to secure all systems - Web, IoT, Smartphone, and applications."
how: "We will have (mostly) hands-on sessions on using tools and techniques to find vulnerabilities in real systems."
where: "EE 118."

when: "Every Thursday @ 6:15 pm - 8:00 pm."

course_semester: "Fall 2022"

requirements: "Please make sure that you have a laptop (Linux/MacOS preferred) and have a basic understanding of operating systems."

baseurl: "/purs3cure" # the subpath of your site, e.g. /blog/
url: "http://purs3lab.github.io/" # the base hostname & protocol for your site

schoolname: "Purdue University"
schoolurl: "https://engineering.purdue.edu/ECE"
twitter_username: machiry_msidc

address: |
    Elmore Family School of Electrical and Computer Engineering
    Purdue University
    West Lafayette, IN, USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-93239312-1

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    topics:
        output: true
    lecschedule:
        output: true
    assignments:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
